### ISSUE TITLE
auth: canonicalizeResource crashed on CentOS 7

### ISSUE THREAD

**Issue by abernardobr** [LearnBoost/knox#269] opened 2015-01-06 13:17 UTC
Using: 
* node v0.11.14
* knox: 0.9.1

Parsing a URL w/o any query string on CentOS, returns url.query: null and not url.query: {}.

By calling url.query crashes since it was expecting at least an empty object and now it is null.

```
exports.canonicalizeResource = function(resource){
  var url = parse(resource, true)
    , path = url.pathname
    , buf = [];

  // apply the query string whitelist
  Object.keys(url.query).forEach(function (key) {
      if (whitelist.indexOf(key) != -1) {
          buf.push(key + (url.query[key] ? "=" + url.query[key] : ''));
      }
  });

  return path + (buf.length
    ? '?' + buf.sort().join('&')
    : '');
};
```
 possible fix:

```
exports.canonicalizeResource = function(resource){
  var url = parse(resource, true)
    , path = url.pathname
    , buf = [];

  url.query = url.query == null ? {} : url.query;
  
  // apply the query string whitelist
  Object.keys(url.query).forEach(function (key) {
      if (whitelist.indexOf(key) != -1) {
          buf.push(key + (url.query[key] ? "=" + url.query[key] : ''));
      }
  });

  return path + (buf.length
    ? '?' + buf.sort().join('&')
    : '');
};
```

**Comment by domenic** [comment] 2015-01-09 00:15
Dupe of #250, #251, #252, #253, #256.

**Closed by domenic** 2015-01-09 00:15 UTC
